apiVersion: webgame.webgame.tech/v1
kind: WebGame
metadata:
  labels:
    app.kubernetes.io/name: webgame
    app.kubernetes.io/managed-by: kustomize
  name: webgame-sample
spec:
  # TODO(user): Add fields here
