apiVersion: webgame.webgame.tech/v1
kind: WebGame
metadata:
  labels:
    app.kubernetes.io/name: webgame
    app.kubernetes.io/managed-by: kustomize
  name: webgame-sample
spec:
  displayName: test-webgame-instance
  gameType: "2048"
  ingressClass: nginx
  domain: webgame.metamaker.cn 
  indexPage: /index.html
  serverPort: 80
  image: nginx:latest
  replicas: 1
  imagePullSecrets: []
